config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    collection do
      get 'event_created'
    end
    collection do
      get 'search'
    end
    resources :pics
  end
  resources :toppage, only: [:index] do
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'toppages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :pics
  mount_uploader :image, EventimageUploader

  accepts_nested_attributes_for :pics, allow_destroy: true
end

app/models/pic.rb
class Pic < ApplicationRecord
belongs_to :event
belongs_to :user

mount_uploader :subimage, SubimageUploader
end

app/models/scraping.rb
class Scraping
  def self.pepe_info
  require 'mechanize'
  link = 'http://studio-pepe.com/event.html'

      agent = Mechanize.new
      page = agent.get(link)
      month_rough = page.search('tr')[1]
      month = month_rough.search('strong')[0].inner_text
      event_all =page.search('tr')[2]
      title = page.search('tr')[2]
      event_all =page.search('tr').size
      event_number = event_all-1

      for i in 2..event_number do
       title = page.search('tr')[i]
       day = title.search('td')[0].inner_text
       time = title.search('td')[1].inner_text
       year_month_day =  "2018-#{month.match(/\d+/)}-#{day.match(/\d+/)}"
       event_name = title.search('td strong').inner_text
         if event_name.match(/Mambongo/)
           event = Event.new(name: event_name, prefecture: "東京都" ,eventday: year_month_day, place: "pepe2", image: 'Mambongo.png', status:0 )
         event.save
         elsif event_name.match(/侍韻/)
         event = Event.new(name: event_name, prefecture: "東京都" ,eventday: year_month_day, place: "pepe2", image: 'samurai.png' , status:0 )
                 event.save
         elsif event_name.match(/Pedro Friday/)
         event = Event.new(name: event_name, prefecture: "東京都" ,eventday: year_month_day, place: "pepe2", image: 'pedro.png' , status:0 )
                 event.save
         elsif event_name.match(/MITSALSA/)
         event = Event.new(name: event_name ,prefecture: "東京都" ,eventday: year_month_day, place: "pepe2", image: 'mitp.jpg' , status:0 )
                 event.save
         elsif event_name.match(/キラキラOn2/)
         event = Event.new(name: event_name ,prefecture: "東京都" ,eventday: year_month_day, place: "pepe2", image: 'kirakira.png' , status:0 )
                 event.save
         else
         event = Event.new(name: event_name ,prefecture: "東京都" ,eventday: year_month_day, place: "pepe2", image: 'NoImage.png' , status:0 )
         event.save
         end
      end
    end
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
   @events = Event.where.not(name: [nil, ""]).page(params[:page]).per(6)
     respond_to do |format|
     format.html
     format.json
  end
end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to new_event_pic_path(@event) }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    if params[:keyword].present?
   @search_events = Event.where('name LIKE(?)', "%#{params[:keyword]}%")
    else
    @search_events = Event.where(eventday:params[:date])
    end
   respond_to do |format|
     format.html
     format.json
   end
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :eventday, :place, :image,:prefecture, :address, :detail).merge(status: 1, user_id: current_user.id)
    end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

def new
    @event = Event.find(params[:event_id])
    @pic = Pic.new
  end

  def create
  @pic = Pic.create(set_pic)
  redirect_to root_path
  end

 private

  def set_pic
    params.require(:pic).permit(:event_id).merge(subimage: params[:file], user_id: current_user.id)
  end

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
      @events = Event.where.not(name: [nil, ""]).page(params[:page]).per(6)
       respond_to do |format|
       format.html
       format.json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/events/_form.html.erb
<%= javascript_include_tag "form.js" %>
<div class="form_wrapper">
  <%= form_for(event) do |f| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>
        <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <h1 class = "title_event_new">イベントを作成する</h1>
  <div class = "form_under_wrapper">
    <div class="field">
      <%= f.label :イベント名 %>
    </div>
    <div class="field_input">
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :日時 %>
    </div>
    <div class="field_input">
      <%= f.datetime_field :eventday %>
    </div>
    <div class="field">
      <%= f.label :場所 %>
    </div>
    <div class="field_input">
      <%= f.text_field :place %>
    </div>
    <div class="field">
      <label class="prefecture_select">都道府県</label>
    </div>
    <div class="field_input">
      <select name="event[prefecture]">
        <option value="東京都" selected>東京都</option>
        <option value="北海道">北海道</option>
        <option value="青森県">青森県</option>
        <option value="岩手県">岩手県</option>
        <option value="宮城県">宮城県</option>
        <option value="秋田県">秋田県</option>
        <option value="山形県">山形県</option>
        <option value="福島県">福島県</option>
        <option value="茨城県">茨城県</option>
        <option value="栃木県">栃木県</option>
        <option value="群馬県">群馬県</option>
        <option value="埼玉県">埼玉県</option>
        <option value="千葉県">千葉県</option>
        <option value="神奈川県">神奈川県</option>
        <option value="新潟県">新潟県</option>
        <option value="富山県">富山県</option>
        <option value="石川県">石川県</option>
        <option value="福井県">福井県</option>
        <option value="山梨県">山梨県</option>
        <option value="長野県">長野県</option>
        <option value="岐阜県">岐阜県</option>
        <option value="静岡県">静岡県</option>
        <option value="愛知県">愛知県</option>
        <option value="三重県">三重県</option>
        <option value="滋賀県">滋賀県</option>
        <option value="京都府">京都府</option>
        <option value="大阪府">大阪府</option>
        <option value="兵庫県">兵庫県</option>
        <option value="奈良県">奈良県</option>
        <option value="和歌山県">和歌山県</option>
        <option value="鳥取県">鳥取県</option>
        <option value="島根県">島根県</option>
        <option value="岡山県">岡山県</option>
        <option value="広島県">広島県</option>
        <option value="山口県">山口県</option>
        <option value="徳島県">徳島県</option>
        <option value="香川県">香川県</option>
        <option value="愛媛県">愛媛県</option>
        <option value="高知県">高知県</option>
        <option value="福岡県">福岡県</option>
        <option value="佐賀県">佐賀県</option>
        <option value="長崎県">長崎県</option>
        <option value="熊本県">熊本県</option>
        <option value="大分県">大分県</option>
        <option value="宮崎県">宮崎県</option>
        <option value="鹿児島県">鹿児島県</option>
        <option value="沖縄県">沖縄県</option>
      </select>
    </div>
    <div class="field">
      <%= f.label :住所 %>
    </div>
    <div class="field_input">
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label :詳細 %>
    </div>
    <div class="field_input">
      <%= f.text_field :detail %>
    </div>
    <div class="field">
      <%= f.label :画像 %>
    </div>
    <div class="field_input">
      <%= f.file_field :image %>
    </div>
    <div class="preview"></div>
  </div>
    <div class="actions">
      <%= f.submit value: '次へ', :class=>"form_submit_button" %>
    </div>
    <%= link_to '戻る', events_path , :class=>"form_back_button" %>
  <% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/event_created.html.erb
<h1>作成したイベント</h1>

app/views/events/index.html.erb
<%= javascript_include_tag "search.js" %>
<%= javascript_include_tag "event_index.js" %>
  <%= render 'shared/header' %>
  <script>
  $(function() {
    $("#datepicker").datepicker();
    $("#datepicker").datepicker("option", "showOn", 'button');
    $("#datepicker").datepicker("option", "buttonImageOnly", true);
    $("#datepicker").datepicker("option", "buttonImage", '/images/calendar.png');
  });
</script>
  <div id = "event_search_result"></div>
<a href = "<%= path_to_prev_page(@events) %>" class = "prev" >
  Prev
  </a>
<a href = "<%= path_to_next_page(@events) %>" class = "next">
  Next
</a>

<div class = "wrapper">
  <div class = "button_wrapper">
    <div class = "search_date" >日付<input type="hidden" id="datepicker" ></div>
    <div class = "search_place">場所</div>
    <div class = "search_instructor">インストラクター</div>
  </div>
  <div class = "each_wrapper">
    <% @events.each do |event| %>
      <div id = "event_card" class="card position_card" style="width: 20rem;">
        <% if event.status == true %>
          <%= image_tag  event.image , :class=> "rcard-img-top",:size => '300x250' %>
        <% else %>
          <%= image_tag "/images/#{event.image.to_s.split('/')[5]}", :class=> "rcard-img-top",:size => '300x250'%>
        <% end %>
        <div class="card-body">
          <p class="card-text"><%= event.eventday.month %>月<%= event.eventday.day %>日</p>
          <span class="card-title" data-title = "#{event.name}"><%= event.name %></span>
          <a href="#" class="btn btn-primary">イベント詳細</a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<%= render 'shared/header' %>
<div id="carouselExampleIndicators" class="carousel slide showcarousel" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <% if @event.status == false %>
          <%= image_tag "/images/#{@event.image.to_s.split('/')[5]}", :class=> "d-block w-100",:size => '300x250'%>
      <% else %>
           <%= image_tag  @event.image , :class=> "d-block w-100",:size => '350x250' %>
      <% end %>
    </div>
    <% if @event.pics.present? %>
      <div class="carousel-item">
        <%= image_tag  @event.pics.first.subimage , :class=> "d-block w-100",:size => '350x250' %>
      </div>
    <% end %>
    <% if @event.pics.second.present? %>
      <div class="carousel-item">
        <%= image_tag  @event.pics.second.subimage , :class=> "d-block w-100",:size => '350x250' %>
      </div>
    <% end %>
    <% if @event.pics.third.present? %>
      <div class="carousel-item">
        <%= image_tag  @event.pics.third.subimage , :class=> "d-block w-100",:size => '350x250' %>
      </div>
    <% end %>
    <% if @event.pics.fourth.present? %>
      <div class="carousel-item">
        <%= image_tag  @event.pics.fourth.subimage , :class=> "d-block w-100",:size => '350x250' %>
      </div>
    <% end %>
    <% if @event.pics.fifth.present? %>
      <div class="carousel-item">
        <%= image_tag  @event.pics.fifth.subimage , :class=> "d-block w-100",:size => '350x250' %>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<hr>
<div class = "event_contents_wrapper">
  <p>
    <strong class = "event_title_showpage"><%= @event.name %></strong>
  </p>
<hr>
  <p class = "event_date_showpage">
    <strong>Date:</strong>
    <%= @event.eventday.month %>月<%= @event.eventday.day %>日
  </p>
<hr>
  <p class = "event_date_showpage">
    <strong>Place:</strong>
    <%= @event.place %>
  </p>
  <p class = "event_date_showpage">
    <strong>住所:</strong>
    <%= @event.address %>
  </p>
<hr>
  <p class = "event_date_showpage">
    <strong>詳細:</strong>
    <%= @event.detail %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baila</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <body>
     <%= yield %>
    </body>
</html>

app/views/pics/new.html.erb
                <style>
                  .dropzone {
                    border: 2px dashed #b4bcc2;
                    @include border-radius(4px);
                  }
              </style>
                <script type="text/javascript">
                  Dropzone.options.myDropzone = {
                    parallelUploads: 1,
                    maxFiles: 5,
                    addRemoveLinks: true,
                  };
                </script>

                <%= form_for [@event, @pic], html:{multipart: true, class:"dropzone", id:"my-dropzone" } do |f| %>
                <%= f.hidden_field :event_id, value: @event.id %>
                <%= link_to '次へ', root_path, class: 'btn' %>
                <% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= image_tag  'bailamos.png',:size => '180x50' %>
      </li>
      <li>
      <%= form_tag('/events/search', method: :get) do %>
       <input class="search__query" name="keyword" placeholder="イベント名で検索" type="text" value=""><button class="btn-search" title="検索" type="submit"><i class="icon-search"></i></button></input>
      <% end %>
      </li>
      <li class="nav-item letter">
      <%= link_to "Home", root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item letter">
        <a class="nav-link" href="#">lesson</a>
      </li>
      <li class="nav-item letter">
        <a class="nav-link" href="#">teacher</a>
      </li>
      <li class="nav-item dropdown letter">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          イベント
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "イベント一覧", events_path, class: 'dropdown-item' %>
          <%= link_to "イベントを作成", new_event_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to "作成イベントの編集", event_created_events_path, class: 'dropdown-item' %>
        </div>
      </li>
      <li class="nav-item letter">
        <a class="nav-link disabled" href="#">Space</a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item letter">
         <%= link_to "ログアウト", destroy_user_session_path, method: :delete , class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item letter">
            <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item letter">
          <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/toppages/index.html.erb
<%= javascript_include_tag "event_index.js" %>
<%= render 'shared/header' %>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag  'DD5.jpg', :class=> "d-block w-100",:size => '700x500' %>
    </div>
    <div class="carousel-item">
     <%= image_tag  'daniel.jpg', :class=> "d-block w-100",:size => '700x500' %>
    </div>
    <div class="carousel-item">
    <%= image_tag  'daniel2.jpg', :class=> "d-block w-100",:size => '700x500' %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<a href = "<%= path_to_prev_page(@events) %>" class = "prev" >
  Prev
  </a>
<a href = "<%= path_to_next_page(@events) %>" class = "next">
  Next
</a>
<div class = "wrapper">
<span class = "contents_title">開催予定のイベント</span>
  <% @events.each do |event| %>
    <div id = "event_card" class="card position_card" style="width: 20rem;">
      <% if event.status == false %>
        <%= image_tag "/images/#{event.image.to_s.split('/')[5]}", :class=> "rcard-img-top",:size => '300x250'%>
      <% else %>
         <%= image_tag  event.image , :class=> "rcard-img-top",:size => '300x250' %>
      <% end %>
      <div class="card-body">
        <p class="card-text"><%= event.eventday.month %>月<%= event.eventday.day %>日</p>
        <span class="card-title" data-title = "#{event.name}"><%= event.name %></span>
        <%= link_to 'イベント詳細', event_path(event), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

<span class = "secondtitle">インストラクターの紹介</span>
   <div><%= image_tag  'terry.jpg', :class=> "rounded instructor_info",:size => '260x260' %></div>